name: Feature Request
description: Suggest a new cipher or feature
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide details below.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Cipher Implementation
        - CLI Enhancement
        - API Improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear description of what you want to happen
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the use case and why this feature would be valuable
      placeholder: This would help with...
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Proposed Implementation
      description: If you have ideas on how to implement this, please share
      placeholder: This could be implemented by...